__shared: &__shared
  - .github/filter-packages/for-eslint.yaml
  - .github/workflows/lint.yaml
  - .node-version
  - pnpm-lock.yaml
  - packages/shared/eslint.config.js

misskey-reversi:
  - *__shared
  - packages/misskey-reversi/**/*.{js,cjs,mjs,jsx,ts,tsx,vue,json}

misskey-bubble-game:
  - *__shared
  - packages/misskey-bubble-game/**/*.{js,cjs,mjs,jsx,ts,tsx,vue,json}

misskey-js:
  - *__shared
  - packages/misskey-js/**/*.{js,cjs,mjs,jsx,ts,tsx,vue,json}

backend:
  - *__shared
  - packages/backend/**/*.{js,cjs,mjs,jsx,ts,tsx,vue,json}

sw:
  - *__shared
  - packages/sw/**/*.{js,cjs,mjs,jsx,ts,tsx,vue,json}

icons-subsetter:
  - *__shared
  - packages/icons-subsetter/**/*.{js,cjs,mjs,jsx,ts,tsx,vue,json}

frontend-shared:
  - *__shared
  - packages/frontend-shared/**/*.{js,cjs,mjs,jsx,ts,tsx,vue,json}

frontend:
  - *__shared
  - packages/frontend/**/*.{js,cjs,mjs,jsx,ts,tsx,vue,json}

frontend-embed:
  - *__shared
  - packages/frontend-embed/**/*.{js,cjs,mjs,jsx,ts,tsx,vue,json}
