name: Check versions

on:
  push:
    branches:
      - develop
      - main
    paths:
      - .github/workflows/check-versions.yaml
      - .devcontainer/devcontainer.json
      - Dockerfile
      - package.json
      - .node-version

  pull_request:
    branches:
      - develop
      - main
    paths:
      - .github/workflows/check-versions.yaml
      - .devcontainer/devcontainer.json
      - Dockerfile
      - package.json
      - .node-version

concurrency:
  group: >-
    ${{ github.workflow }}-
    ${{ github.event.pull_request.head.repo.full_name || github.repository }}-
    ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  check-node-versions:
    name: Check Node versions
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      - name: Detect version (.node-version)
        run: |
          EXPECTED_VERSION="$(cat .node-version)"
          [[ -n "$EXPECTED_VERSION" ]] || exit 1
          echo "EXPECTED_VERSION=${EXPECTED_VERSION}" >> "$GITHUB_ENV"
          echo "::notice::Detected version: ${EXPECTED_VERSION}"

      - name: Check version (Dockerfile)
        run: |
          grep -Eq "^ARG NODE_VERSION=${EXPECTED_VERSION}(-.*)?$" Dockerfile

      - name: Check version (devcontainer.json)
        run: |
          ACTUAL_VERSION="$(jq -er '
            .features
            | to_entries
            | map(select(.key | startswith("ghcr.io/devcontainers/features/node:")))
            | first
            | .value.version
          ' .devcontainer/devcontainer.json)"
          [[ "$ACTUAL_VERSION" == "$EXPECTED_VERSION" ]] || exit 1

  check-pnpm-versions:
    name: Check pnpm versions
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      - name: Detect version (packageManager)
        run: |
          EXPECTED_VERSION="$(jq -er '.packageManager | select(startswith("pnpm@")) | split("@")[1]' package.json)"
          echo "EXPECTED_VERSION=${EXPECTED_VERSION}" >> "$GITHUB_ENV"
          echo "::notice::Detected version: ${EXPECTED_VERSION}"

      - name: Check version (devDependencies)
        run: |
          ACTUAL_VERSION="$(jq -er '.devDependencies.pnpm' package.json)"
          [[ "$ACTUAL_VERSION" == "$EXPECTED_VERSION" ]] || exit 1

      # - name: Check version (Dockerfile)
      #   run: |
      #     grep -qx "ARG PNPM_VERSION=${EXPECTED_VERSION}" Dockerfile

      - name: Check version (devcontainer.json)
        run: |
          ACTUAL_VERSION="$(jq -er '
            .features
            | to_entries
            | map(select(.key | startswith("ghcr.io/devcontainers-extra/features/pnpm:")))
            | first
            | .value.version
          ' .devcontainer/devcontainer.json)"
          [[ "$ACTUAL_VERSION" == "$EXPECTED_VERSION" ]] || exit 1
