name: Publish Docker image
run-name: Publish Docker image (${{ github.ref_type == 'tag' && github.ref_name || 'nightly' }})

on:
  push:
    branches:
      - taiyme
    tags:
      - '*-taiyme.*'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-22.04
    outputs:
      meta_version: ${{ steps.meta.outputs.version }}
      meta_tags: ${{ steps.meta.outputs.tags }}
      meta_labels: ${{ steps.meta.outputs.labels }}
      meta_annotations: ${{ steps.meta.outputs.annotations }}
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          ref: ${{ github.sha }}
          fetch-depth: 1

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5.7.0
        env:
          DOCKER_METADATA_SHORT_SHA_LENGTH: 9
          DOCKER_METADATA_SET_OUTPUT_ENV: false
        with:
          images: ${{ vars.DOCKER_IMAGE_NAME }}
          tags: |
            type=raw,priority=1300,value=${{ github.ref_name }},prefix=,suffix=,enable=${{ github.ref_type == 'tag' }}
            type=raw,priority=1200,value=latest,prefix=,suffix=,enable=${{ github.ref_type == 'tag' }}
            type=raw,priority=1200,value=nightly,prefix=,suffix=,enable=${{ github.ref_type != 'tag' }}
            type=sha,priority=1100,format=short,prefix=,suffix=,enable=true

  build-and-push:
    name: Build and Push
    runs-on: ${{ matrix.value.os }}
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        value:
          - os: ubuntu-22.04
            platform: linux/amd64
          - os: ubuntu-22.04-arm
            platform: linux/arm64
    steps:
      - name: Checkout ${{ github.sha }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          ref: ${{ github.sha }}
          fetch-depth: 1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push by digest
        id: build
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          platforms: ${{ matrix.value.platform }}
          provenance: false
          labels: ${{ needs.prepare.outputs.meta_labels }}
          annotations: ${{ needs.prepare.outputs.meta_annotations }}
          cache-from: type=gha,scope=platform-${{ runner.os }}-${{ runner.arch }}
          cache-to: type=gha,mode=max,scope=platform-${{ runner.os }}-${{ runner.arch }}
          outputs: type=image,name=${{ vars.DOCKER_IMAGE_NAME }},push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        env:
          digest: ${{ steps.build.outputs.digest }}
        run: |
          mkdir -p ${{ runner.temp }}/digests
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: digests-${{ runner.os }}-${{ runner.arch }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge-images:
    name: Merge images
    runs-on: ubuntu-22.04
    needs:
      - prepare
      - build-and-push
    steps:
      - name: Download digests
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          pattern: digests-*
          path: ${{ runner.temp }}/digests
          merge-multiple: true

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and Push manifest list
        working-directory: ${{ runner.temp }}/digests
        env:
          meta_tags_list: ${{ needs.prepare.outputs.meta_tags }}
        run: |
          docker buildx imagetools create \
            $((jq -R . | jq -scr 'map("--tag " + .) | join(" ")') <<< "$meta_tags_list") \
            $(printf '${{ vars.DOCKER_IMAGE_NAME }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect \
            ${{ vars.DOCKER_IMAGE_NAME }}:${{ needs.prepare.outputs.meta_version }}
