name: Filter packages

on:
  workflow_call:
    inputs:
      filters:
        type: string
        required: true
    outputs:
      packages:
        value: ${{ jobs.filter-packages.outputs.packages }}

# zizmor: ignore[concurrency-limits]

permissions: {}

jobs:
  filter-packages:
    name: Filter packages
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
      pull-requests: read # dorny/paths-filter の実行に必要
    outputs:
      packages: ${{ steps.result.outputs.packages }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Filter
        id: filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        with:
          filters: ${{ inputs.filters }}

      - name: Set actual_packages
        env:
          output_changes: ${{ steps.filter.outputs.changes }}
        run: |
          echo "actual_packages=${output_changes:-[]}" >> "$GITHUB_ENV"

      - name: Set expected_packages
        run: |
          expected_packages="$(pnpm ls -r --depth=-1 --json | jq -c 'map(.name)')"
          echo "expected_packages=${expected_packages:-[]}" >> "$GITHUB_ENV"

      - name: Extract packages
        id: result
        run: |
          packages="$( \
            jq -c -n \
            --argjson actual "$actual_packages" \
            --argjson expected "$expected_packages" \
            -- '$actual | map(select(. as $item | $expected | index($item)))' \
          )"
          echo "packages=${packages:-[]}" >> "$GITHUB_OUTPUT"
