name: Pull Request Labeler

on:
  pull_request_target: # zizmor: ignore[dangerous-triggers]

# zizmor: ignore[concurrency-limits]

permissions: {}

jobs:
  triage:
    name: Triage
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      pull-requests: write # actions/labeler の実行に必要
    steps:
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yaml
          sync-labels: true
