name: Lint

on:
  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main

concurrency:
  group: >-
    ${{ github.workflow }}-
    ${{ github.event.pull_request.head.repo.full_name || github.repository }}-
    ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  filter-packages-eslint:
    name: Filter packages (ESLint)
    uses: ./.github/workflows/filter-packages.yaml
    permissions:
      contents: read
      pull-requests: read # dorny/paths-filter の実行に必要
    with:
      filters: .github/filter-packages/for-eslint.yaml

  filter-packages-typecheck:
    name: Filter packages (TypeCheck)
    uses: ./.github/workflows/filter-packages.yaml
    permissions:
      contents: read
      pull-requests: read # dorny/paths-filter の実行に必要
    with:
      filters: .github/filter-packages/for-typecheck.yaml

  eslint:
    name: ESLint
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
    needs:
      - filter-packages-eslint
    if: ${{ needs.filter-packages-eslint.outputs.packages != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.filter-packages-eslint.outputs.packages) }}
    env:
      cache-path: ${{ github.workspace }}/node_modules/.cache/eslint-${{ matrix.package }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Create cache key
        id: cache-keys
        env:
          package: ${{ matrix.package }}
          lockfile_hash: ${{ hashFiles('**/pnpm-lock.yaml') }}
        run: |
          cache_name="eslint-${package}"
          cache_platform="${RUNNER_OS}-${RUNNER_ARCH}"
          cache_primary_key="${cache_name}-${cache_platform}-${lockfile_hash}-${GITHUB_SHA}"
          cache_restore_key="${cache_name}-${cache_platform}-${lockfile_hash}-"
          echo "primary=${cache_primary_key}" >> "$GITHUB_OUTPUT"
          echo "restore=${cache_restore_key}" >> "$GITHUB_OUTPUT"

      - name: Cache ESLint
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ${{ env.cache-path }}
          key: ${{ steps.cache-keys.outputs.primary }}
          restore-keys: ${{ steps.cache-keys.outputs.restore }}

      - name: Run ESLint
        env:
          package: ${{ matrix.package }}
          cache_location: ${{ env.cache-path }}
        run: |
          pnpm --filter "$package" \
            run eslint \
            --cache \
            --cache-location "$cache_location" \
            --cache-strategy content

  typecheck:
    name: TypeCheck
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
    needs:
      - filter-packages-typecheck
    if: ${{ needs.filter-packages-typecheck.outputs.packages != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.filter-packages-typecheck.outputs.packages) }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build
        env:
          package: ${{ matrix.package }}
        run: |
          pnpm --filter "${package}^..." \
            run build

      - name: Run TypeCheck
        env:
          package: ${{ matrix.package }}
        run: |
          pnpm --filter "$package" \
            run typecheck
