name: Lint (locales)

on:
  push:
    branches:
      - develop
      - main
    paths:
      - .github/workflows/lint-locales.yaml
      - packages/i18n/**/*
      - locales/**/*

  pull_request:
    branches:
      - develop
      - main
    paths:
      - .github/workflows/lint-locales.yaml
      - packages/i18n/**/*
      - locales/**/*

concurrency:
  group: >-
    ${{ github.workflow }}-
    ${{ github.event.pull_request.head.repo.full_name || github.repository }}-
    ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  verify-locales:
    name: Verify locales
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Build
        run: |
          pnpm --filter i18n \
            run build

      - name: Verify locales
        run: |
          pnpm --filter i18n \
            run verify
