name: Publish Docker Image
run-name: Publish Docker Image (${{ github.ref_type == 'tag' && github.ref_name || 'nightly' }})

on:
  push:
    branches:
      - develop
    tags:
      - '*-taiyme.*'

# zizmor: ignore[concurrency-limits]

permissions: {}

jobs:
  meta:
    name: Extract Metadata
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    outputs:
      registry: ${{ steps.vars.outputs.registry }}
      image-name: ${{ steps.vars.outputs.image-name }}
      version: ${{ steps.meta.outputs.version }}
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
      annotations: ${{ steps.meta.outputs.annotations }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      - name: Set Variables
        id: vars
        env:
          REGISTRY: ghcr.io
        run: |
          echo "registry=${REGISTRY}" >> "$GITHUB_OUTPUT"
          echo "image-name=${REGISTRY}/${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

      - name: Extract Metadata
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: index
          DOCKER_METADATA_SHORT_SHA_LENGTH: 9
          DOCKER_METADATA_SET_OUTPUT_ENV: false
        with:
          images: ${{ steps.vars.outputs.image-name }}
          tags: |
            type=raw,priority=1300,value=${{ github.ref_name }},prefix=,suffix=,enable=${{ github.ref_type == 'tag' }}
            type=raw,priority=1200,value=latest,prefix=,suffix=,enable=${{ github.ref_type == 'tag' }}
            type=raw,priority=1200,value=nightly,prefix=,suffix=,enable=${{ github.ref_type != 'tag' }}
            type=sha,priority=1100,format=short,prefix=,suffix=,enable=true

  build-and-push:
    name: Build and Push
    runs-on: ${{ matrix.value.os }}
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write # Required for publishing docker image.
    needs:
      - meta
    strategy:
      fail-fast: false
      matrix:
        value:
          - os: ubuntu-24.04
            platform: linux/amd64
          - os: ubuntu-24.04-arm
            platform: linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ needs.meta.outputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Variables
        id: vars
        env:
          PLATFORM: ${{ matrix.value.platform }}
        run: |
          PLATFORM_PAIR="${PLATFORM//\//-}"
          echo "platform-pair=${PLATFORM_PAIR}" >> "$GITHUB_OUTPUT"

          REPO_PAIR="${GITHUB_REPOSITORY//\//-}"
          REPO_PAIR="${REPO_PAIR,,}"
          CACHE_SCOPE="buildkit--${REPO_PAIR}--${PLATFORM_PAIR}"
          echo "cache-scope=${CACHE_SCOPE}" >> "$GITHUB_OUTPUT"

      - name: Build and Push by digest
        id: build
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: .
          platforms: ${{ matrix.value.platform }}
          labels: ${{ needs.meta.outputs.labels }}
          cache-from: >-
            type=gha,
            scope=${{ steps.vars.outputs.cache-scope }}
          cache-to: >-
            type=gha,
            mode=max,
            scope=${{ steps.vars.outputs.cache-scope }}
          outputs: >-
            type=image,
            name=${{ needs.meta.outputs.image-name }},
            push-by-digest=true,
            name-canonical=true,
            oci-mediatypes=true,
            compression=zstd,
            compression-level=3,
            force-compression=true,
            push=true

      - name: Export digest
        env:
          IMAGE_DIGEST: ${{ steps.build.outputs.digest }}
        run: |
          mkdir -p /tmp/digests
          touch "/tmp/digests/${IMAGE_DIGEST#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: digests--${{ steps.vars.outputs.platform-pair }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge-and-attest:
    name: Merge and Attest
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write # Required for publishing docker image.
      id-token: write # Required to generate build attestations.
      attestations: write # Required to generate build attestations.
      artifact-metadata: write # Required to generate build attestations.
    needs:
      - meta
      - build-and-push
    steps:
      - name: Download digests
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          pattern: digests--*
          path: /tmp/digests
          merge-multiple: true

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ needs.meta.outputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Multi-arch manifest
        env:
          IMAGE_NAME: ${{ needs.meta.outputs.image-name }}
          META_ANNOTATIONS: ${{ needs.meta.outputs.annotations }}
          META_TAGS: ${{ needs.meta.outputs.tags }}
        working-directory: /tmp/digests
        run: |
          TAG_ARGS=()
          while IFS= read -r tag; do
            TAG_ARGS+=(--tag "$tag")
          done <<< "$META_TAGS"

          ANNOTATION_ARGS=()
          while IFS= read -r annotation; do
            ANNOTATION_ARGS+=(--annotation "$annotation")
          done <<< "$META_ANNOTATIONS"

          DIGEST_ARGS=()
          for f in *; do
            DIGEST=${f##*/}
            DIGEST_ARGS+=("$IMAGE_NAME@sha256:$DIGEST")
          done

          docker buildx imagetools create \
            "${TAG_ARGS[@]}" \
            "${ANNOTATION_ARGS[@]}" \
            "${DIGEST_ARGS[@]}"

      - name: Export Multi-arch digest
        id: export
        env:
          IMAGE_NAME: ${{ needs.meta.outputs.image-name }}
          META_VERSION: ${{ needs.meta.outputs.version }}
        run: |
          MULTIARCH_DIGEST="$(
            docker buildx imagetools inspect \
              "$IMAGE_NAME:$META_VERSION" \
              --format "{{json .Manifest}}" | \
              jq -cr '.digest'
          )"
          echo "multiarch-digest=${MULTIARCH_DIGEST}" >> "$GITHUB_OUTPUT"

      - name: Attest
        uses: actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6 # v4.2.0
        with:
          subject-name: ${{ needs.meta.outputs.image-name }}
          subject-digest: ${{ steps.export.outputs.multiarch-digest }}
          push-to-registry: true

      - name: Inspect
        if: ${{ always() }}
        env:
          IMAGE_NAME: ${{ needs.meta.outputs.image-name }}
          META_VERSION: ${{ needs.meta.outputs.version }}
          MULTIARCH_DIGEST: ${{ steps.export.outputs.multiarch-digest }}
        run: |
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "META_VERSION: $META_VERSION"
          echo "MULTIARCH_DIGEST: $MULTIARCH_DIGEST"

          docker buildx imagetools inspect \
            "$IMAGE_NAME:$META_VERSION"
