name: Test (frontend)

on:
  push:
    branches:
      - develop
      - main
    paths:
      - .github/workflows/test-frontend.yaml
      - .github/misskey/test.yml
      - packages/frontend/**/*
      - packages/frontend-embed/**/*
      - packages/frontend-shared/**/*
      - packages/backend/**/*
      - packages/mfm-js/**/*
      - packages/misskey-js/**/*

  pull_request:
    branches:
      - develop
      - main
    paths:
      - .github/workflows/test-frontend.yaml
      - .github/misskey/test.yml
      - packages/frontend/**/*
      - packages/frontend-embed/**/*
      - packages/frontend-shared/**/*
      - packages/backend/**/*
      - packages/mfm-js/**/*
      - packages/misskey-js/**/*

concurrency:
  group: >-
    ${{ github.workflow }}-
    ${{ github.event.pull_request.head.repo.full_name || github.repository }}-
    ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
    env:
      MISSKEY_CONFIG_YML: ci_config.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Copy config
        run: |
          cp .github/misskey/test.yml ".config/${MISSKEY_CONFIG_YML}"

      - name: Build
        run: |
          pnpm run build

      - name: Test
        run: |
          pnpm --filter frontend \
            run test-and-coverage

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        browser:
          - chrome
    services:
      postgres:
        image: postgres:18@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
        ports:
          - 54312:5432
        env:
          POSTGRES_DB: test-misskey
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:7@sha256:24ea35ee039d7345bef2377611e3b1a615231746de4cfea74c1414575ee56167
        ports:
          - 56312:6379
    env:
      MISSKEY_CONFIG_YML: ci_config.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      # https://github.com/cypress-io/cypress-docker-images/issues/150
      # - name: Install mplayer for FireFox
      #   if: ${{ matrix.browser == 'firefox' }}
      #   run: |
      #     sudo apt install mplayer -y

      # - uses: browser-actions/setup-firefox@955a5d42b5f068a8917c6a4ff1656a2235c66dfb # v1.5.2
      #   if: ${{ matrix.browser == 'firefox' }}

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Copy config
        run: |
          cp .github/misskey/test.yml ".config/${MISSKEY_CONFIG_YML}"

      - name: Build
        run: |
          pnpm run build

      # https://github.com/cypress-io/cypress/issues/4351#issuecomment-559489091
      - name: ALSA Env
        run: |
          echo -e 'pcm.!default {\n type hw\n card 0\n}\n\nctl.!default {\n type hw\n card 0\n}' > ~/.asoundrc

      # XXX: This tries reinstalling Cypress if the binary is not cached
      # Remove this when the cache issue is fixed
      - name: Cypress install
        run: |
          pnpm exec cypress install

      - name: Cypress run
        uses: cypress-io/github-action@dace029018fcdf86e0df89a31bc3cfa5b32570d8 # v7.3.0
        timeout-minutes: 15
        with:
          install: false
          start: pnpm run start:test
          wait-on: 'http://localhost:61812'
          headed: true
          browser: ${{ matrix.browser }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ failure( )}}
        with:
          name: ${{ matrix.browser }}-cypress-screenshots
          path: cypress/screenshots

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ always() }}
        with:
          name: ${{ matrix.browser }}-cypress-videos
          path: cypress/videos
