name: Test (backend)

on:
  push:
    branches:
      - develop
      - main
    paths:
      - .github/workflows/test-backend.yaml
      - .github/misskey/test.yml
      - packages/backend/**/*
      - packages/mfm-js/**/*
      - packages/misskey-js/**/*

  pull_request:
    branches:
      - develop
      - main
    paths:
      - .github/workflows/test-backend.yaml
      - .github/misskey/test.yml
      - packages/backend/**/*
      - packages/mfm-js/**/*
      - packages/misskey-js/**/*

concurrency:
  group: >-
    ${{ github.workflow }}-
    ${{ github.event.pull_request.head.repo.full_name || github.repository }}-
    ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        shard:
          - 1
          - 2
          - 3
          - 4
    services:
      postgres:
        image: postgres:18@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
        ports:
          - 54312:5432
        env:
          POSTGRES_DB: test-misskey
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:7@sha256:24ea35ee039d7345bef2377611e3b1a615231746de4cfea74c1414575ee56167
        ports:
          - 56312:6379
      meilisearch:
        image: getmeili/meilisearch:v1.40.0@sha256:54f0cca5442af756ff0254e3307cfd846605facf9b6989f571f6b1a96deb0c7c
        ports:
          - 57712:7700
        env:
          MEILI_NO_ANALYTICS: true
          MEILI_ENV: development
    env:
      MISSKEY_CONFIG_YML: ci_config.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Setup FFmpeg
        uses: ./.github/actions/setup-ffmpeg

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Copy config
        run: |
          cp .github/misskey/test.yml ".config/${MISSKEY_CONFIG_YML}"

      - name: Build
        run: |
          pnpm run build

      - name: Test
        env:
          shard: ${{ matrix.shard }}/${{ strategy.job-total }}
        run: |
          pnpm --filter backend \
            run test-and-coverage --shard "$shard"

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        shard:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
    services:
      postgres:
        image: postgres:18@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
        ports:
          - 54312:5432
        env:
          POSTGRES_DB: test-misskey
          POSTGRES_HOST_AUTH_METHOD: trust
      redis:
        image: redis:7@sha256:24ea35ee039d7345bef2377611e3b1a615231746de4cfea74c1414575ee56167
        ports:
          - 56312:6379
    env:
      MISSKEY_CONFIG_YML: ci_config.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Setup FFmpeg
        uses: ./.github/actions/setup-ffmpeg

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Copy config
        run: |
          cp .github/misskey/test.yml ".config/${MISSKEY_CONFIG_YML}"

      - name: Build
        run: |
          pnpm run build

      - name: Test
        env:
          shard: ${{ matrix.shard }}/${{ strategy.job-total }}
        run: |
          pnpm --filter backend \
            run test-and-coverage:e2e --shard "$shard"

  migration-tests:
    name: Migration Tests
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    permissions:
      contents: read
    services:
      postgres:
        image: postgres:18@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
        ports:
          - 54312:5432
        env:
          POSTGRES_DB: test-misskey
          POSTGRES_HOST_AUTH_METHOD: trust
    env:
      MISSKEY_CONFIG_YML: ci_config.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 1
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Setup FFmpeg
        uses: ./.github/actions/setup-ffmpeg

      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile

      - name: Copy config
        run: |
          cp .github/misskey/test.yml ".config/${MISSKEY_CONFIG_YML}"

      - name: Build
        run: |
          pnpm run build

      - name: Run migrations
        run: |
          pnpm --filter backend \
            run migrate

      - name: Check migrations
        run: |
          pnpm --filter backend \
            run check-migrations
